[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*", "lib/*"]

[workspace.dependencies]
hdi = "=0.3.4"
hdk = "=0.2.4"
serde = "=1.0.166"

[workspace.dependencies.demo]
path = "dnas/demo/zomes/coordinator/demo"

[workspace.dependencies.demo_integrity]
path = "dnas/demo/zomes/integrity/demo"

[workspace.dependencies.prefix_index]
path = "lib/prefix_index"
